In [1]:
import pymysql
import pymongo
from pymongo import MongoClient
from pymongo.errors import ConnectionFailure
import datetime
import decimal
import pandas as pd

### Connect to MySQL: emr database (READ)

In [2]:
mysql_conn = pymysql.connect(
    host='mdsmysql.sci.pitt.edu',
    user='kwc15',
    password='Mds_4204465@',
    database='emr'
)
mysql_cursor = mysql_conn.cursor(pymysql.cursors.DictCursor)

with mysql_conn.cursor() as cursor:
    cursor.execute("SELECT VERSION()")
    version = cursor.fetchone()
    print("MySQL version:", version[0])

MySQL version: 8.4.5

### Connect to MongoDB

In [3]:
# using the connection string that worked in MongoDB Compass
uri = "mongodb://kwc15:Mds_4204465%40@mdsmongodb.sci.pitt.edu:27017/"

mongo_client = MongoClient(uri)
mongo_db = mongo_client['kwc15']
mongo_client.admin.command('ping')  # Trigger connection
print("✅ Successfully connected to MongoDB with authentication.")
print("Available databases:", mongo_client.list_database_names())

✅ Successfully connected to MongoDB with authentication.
Available databases: ['etl', 'kwc15', 'sakila']

### Create helper function to sanitize data for MongoDB

In [4]:
def sanitize_for_mongo(doc):
    if isinstance(doc, dict):
        return {k: sanitize_for_mongo(v) for k, v in doc.items()}
    elif isinstance(doc, list):
        return [sanitize_for_mongo(item) for item in doc]
    elif isinstance(doc, decimal.Decimal):
        return float(doc)
    elif isinstance(doc, datetime.date) and not isinstance(doc, datetime.datetime):
        return datetime.datetime.combine(doc, datetime.time())
    else:
        return doc

### Create helper function to fetch, sanitize, and insert collections

In [7]:
def migrate_table_to_collection(sql_query, mongo_collection, transform_func=None):
    mysql_cursor.execute(sql_query)
    rows = mysql_cursor.fetchall()
    if transform_func:
        rows = [transform_func(row) for row in rows]
    sanitized_rows = [sanitize_for_mongo(row) for row in rows]
    if sanitized_rows:
        mongo_collection.insert_many(sanitized_rows)

### Migrate Patients (referenced)

In [8]:
migrate_table_to_collection("SELECT * FROM patient", mongo_db.patients)

### Migrate Providers (referenced)

In [10]:
migrate_table_to_collection("SELECT * FROM provider", mongo_db.providers)

### Migrate Visits and Embed Symptoms, Diagnoses, Procedures, Labs, and Patient/Providers with linkages

In [30]:
mysql_cursor.execute("SELECT * FROM visit")
visits = mysql_cursor.fetchall()
for visit in visits:
    # Embed symptoms: Array of strings
    mysql_cursor.execute("""
        SELECT DISTINCT s.note FROM visit_symptom vs
        JOIN symptom s ON vs.symptom_id = s.symptom_id
        WHERE vs.visit_id = %s""", (visit['visit_id']))
    visit['symptoms'] = [row['note'] for row in mysql_cursor.fetchall()]

    # Embed diagnoses: Array of objects
    mysql_cursor.execute("""
        SELECT DISTINCT d.name, d.icd10_code FROM visit_diagnosis vd
        JOIN diagnosis d on vd.diagnosis_id = d.diagnosis_id
        WHERE vd.visit_id = %s""", (visit['visit_id'],))
    visit['diagnoses'] = mysql_cursor.fetchall()

    # Embed procedures: Array of objects
    mysql_cursor.execute("""
        SELECT DISTINCT cp.proc_name, cp.description FROM visit_procedure vp
        JOIN clinical_procedures cp
        WHERE vp.visit_id = %s""", (visit['visit_id'],))
    visit['procedures'] = mysql_cursor.fetchall()

    # Embed labs: Array of objects
    mysql_cursor.execute("""
        SELECT DISTINCT l.lab_name, l.cpt_code FROM visit_lab vl
        JOIN lab l ON vl.lab_id = l.lab_id
        WHERE vl.visit_id = %s""", (visit['visit_id'],))
    visit['labs'] = mysql_cursor.fetchall()

    # Link ObjectIds for patients and providers
    # Look up the mongodb _id based on the preserved MySQL ID
    patient_doc = mongo_db.patients.find_one({"patient_id": visit['patient_id']})
    provider_doc = mongo_db.providers.find_one({"provider_id": visit['provider_id']})

    if patient_doc:
        visit['patient_ref'] = patient_doc['_id']
    if provider_doc:
        visit['provider_ref'] = provider_doc['_id']

    # Sanitize and insert
    mongo_db.visits.insert_one(sanitize_for_mongo(visit))

print(f"Successfully migrated {len(visits)} visit documents!")

Successfully migrated 306 visit documents!

### Verify ETL Results

In [17]:
# Patients
patients_df = pd.DataFrame(list(mongo_db.patients.find()))
patients_df.head()

,_id,patient_id,first_name,last_name,dob,gender
0,699690a19d664b27a141ad26,1,Megan,Chang,1991-07-07,Female
1,699690a19d664b27a141ad27,2,Billy,Sheppard,2000-05-29,Female
2,699690a19d664b27a141ad28,3,Richard,Bowers,1975-07-22,Male
3,699690a19d664b27a141ad29,4,Tammy,Howard,1964-01-02,Female
4,699690a19d664b27a141ad2a,5,William,Campbell,1947-03-08,Other

In [18]:
# Providers
providers_df = pd.DataFrame(list(mongo_db.providers.find()))
providers_df.head()

                        _id  provider_id first_name last_name        specialty
0  6996914f9d664b27a141ad58            1       Ryan     Brown       Cardiology
1  6996914f9d664b27a141ad59            2     Tanner   Carlson        Neurology
2  6996914f9d664b27a141ad5a            3      Holly     Myers         Oncology
3  6996914f9d664b27a141ad5b            4      Jorge    Strong  Family Medicine
4  6996914f9d664b27a141ad5c            5   Theodore   Barrera      Dermatology

In [31]:
# Visits
visits_df = pd.DataFrame(list(mongo_db.visits.find()))
visits_df.head()

,_id,visit_id,patient_id,provider_id,visit_date,symptoms,diagnoses,procedures,labs,patient_ref,provider_ref
0,6996a0bb9d664b27a141aebc,0,1,21,2024-03-26,[],[],[],[],699690a19d664b27a141ad26,6996914f9d664b27a141ad6c
1,6996a0be9d664b27a141aebd,1,1,6,2024-03-27,[Sudden weakness on one side of the body],"[{'name': 'Psoriasis vulgaris', 'icd10_code': ...",[{'proc_name': 'Transfusion of Nonautologous R...,"[{'lab_name': 'Urea nitrogen; quantitative', '...",699690a19d664b27a141ad26,6996914f9d664b27a141ad5d
2,6996a0be9d664b27a141aebe,2,1,31,2024-04-09,"[Sudden onset of chest pain and dizziness, Dry...",[{'name': 'Noninfective gastroenteritis and co...,[{'proc_name': 'Transfusion of Nonautologous R...,"[{'lab_name': 'Bilirubin; total', 'cpt_code': ...",699690a19d664b27a141ad26,6996914f9d664b27a141ad76
3,6996a0be9d664b27a141aebf,3,1,23,2023-04-22,"[Dry, scaly patches on the skin, Intermittent ...","[{'name': 'Major depressive disorder, recurren...",[{'proc_name': 'Transfusion of Nonautologous R...,"[{'lab_name': 'Vitamin D; 25 hydroxy', 'cpt_co...",699690a19d664b27a141ad26,6996914f9d664b27a141ad6e
4,6996a0be9d664b27a141aec0,4,1,23,2023-09-19,"[Dry, scaly patches on the skin, Tingling and ...","[{'name': 'Acute upper respiratory infection, ...",[{'proc_name': 'Transfusion of Nonautologous R...,"[{'lab_name': 'Vitamin D; 25 hydroxy', 'cpt_co...",699690a19d664b27a141ad26,6996914f9d664b27a141ad6e

### Pull together a JSON of a 3 patient sample

In [34]:
import json
from bson import json_util

def generate_sample_json(db, output_file="sample_output.json", num_patients=3):
    # fetch 3 patients from patients collection in mongo
    patients = list(mongo_db.patients.find().limit(num_patients))
    
    sample_data = []
    
    for patient in patients:
        # use the ObjectId to find all visits for this patient
        # query the visits collection using the patient's _id
        patient_visits = list(mongo_db.visits.find({"patient_ref": patient["_id"]}))
        
        # combine into a "Patient History" structure
        patient_history = {
            "patient_info": patient,
            "total_visits": len(patient_visits),
            "visit_history": patient_visits
        }
        sample_data.append(patient_history)
    
    # write to JSON file
    # use json_util to handle mongo object IDs and dates correctly
    with open(output_file, "w") as f:
        f.write(json_util.dumps(sample_data, indent=4))
    
    print(f"Sample output for {num_patients} patients saved to {output_file}")

# Call the function
generate_sample_json(mongo_db)

Sample output for 3 patients saved to sample_output.json

In [1]:
# --- Close Connections ---
mysql_cursor.close()
mysql_conn.close()
mongo_client.close()

NameError: name 'mysql_cursor' is not defined